name: quick_bills
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  clipboard: ^0.1.3
  fluttertoast: ^8.2.4
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  dotted_decoration: ^2.0.0
  flutter_screenutil: ^5.9.3
  loading_indicator: ^3.1.1
  collection:
  http: ^1.1.2
  path_provider: ^2.1.1
  dio: ^5.3.2
  get: ^4.6.5
  another_flushbar: ^1.12.30
  iconsax: ^0.0.8
  pretty_dio_logger: ^1.3.1
  gif_view: ^1.0.3
  dotted_line:
  hive_flutter:
  flutter_native_contact_picker: ^0.0.10
  flutter_contacts: ^1.1.9+2
  iconly: 
  permission_handler: ^12.0.0+1
  upgrader: ^11.5.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  flutter_svg: ^2.0.9
  share_plus: ^11.0.0
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  url_launcher: 
  country_picker: ^2.0.27
  image: ^4.1.7
  audioplayers: ^5.2.1
  country_state_picker: ^0.0.5
  flutter_inappwebview: ^6.1.5   
  flutter_otp_text_field: ^1.1.0+2
  file_picker: ^10.1.9

  flutter_dotenv: ^5.2.1






  video_player: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - .env

  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
        - asset: assets/fonts/Switzer-Bold.otf
        - asset: assets/fonts/Switzer-Medium.otf
        - asset: assets/fonts/Switzer-Regular.otf
        - asset: assets/fonts/Switzer-SemiBold.otf
        - asset: assets/fonts/Switzer-Thin.otf
