name: jost_pay_wallet
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_custom_dropdown: 3.1.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3
  connectivity_plus: ^5.0.2
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  custom_pin_screen: ^0.5.0
  declarative_refresh_indicator: ^0.1.0
  dotted_border: ^2.1.0
  dotted_decoration: ^2.0.0
  dotted_line: ^3.2.3
  eth_sig_util: ^0.0.9
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_animate: ^3.1.0
  flutter_otp_text_field: ^1.1.0+2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.4
  gauge_indicator: ^0.4.3
  grouped_list: ^5.1.2
  http: ^1.1.2
  intl: ^0.18.1
  linear_progress_bar: 1.1.2
  local_auth: ^2.1.7
  mobile_scanner: ^3.5.5
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  wallet_connect_dart_v2: ^0.0.1
  web3dart: ^2.7.2

dependency_overrides:
  win32: ^5.5.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ie_logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/dashboard/
    - assets/images/splash/
    - assets/images/svg/

  fonts:
    - family: NimbusSanLBol
      fonts:
        - asset: assets/fonts/NimbusSanL-Bol.otf

    - family: NimbusSanLBolIta
      fonts:
        - asset: assets/fonts/NimbusSanL-BolIta.otf

    - family: NimbusSanLRegular
      fonts:
        - asset: assets/fonts/NimbusSanL-Reg.otf

    - family: NimbusSanLRegularItalic
      fonts:
        - asset: assets/fonts/NimbusSanL-RegIta.otf

    - family: VahidRegular
      fonts:
        - asset: assets/fonts/XM-Vahid-Reg.otf

    - family: VahidRegularItalic
      fonts:
        - asset: assets/fonts/XM-Vahid-RegIta.otf

    - family: VahidBold
      fonts:
        - asset: assets/fonts/XM-Vahid-Bol.otf

    - family: VahidBoldItalic
      fonts:
        - asset: assets/fonts/XM-Vahid-BolIta.otf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Reg.otf

    - family: InterRegularItalic
      fonts:
        - asset: assets/fonts/Inter-RegIta.otf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bol.otf

    - family: InterBoldItalic
      fonts:
        - asset: assets/fonts/Inter-BolIta.otf

    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
