name: jost_pay_wallet
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+7

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  clipboard: ^0.1.3
  fluttertoast: ^8.2.4
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  dotted_decoration: ^2.0.0
  flutter_screenutil: ^5.9.3
  loading_indicator: ^3.1.1
  webview_flutter: 4.10.0 
  collection:
  http: ^1.1.2
  path_provider: ^2.1.1
  dio: ^5.3.2
  get: ^4.6.5
  another_flushbar: ^1.12.30
  iconsax: ^0.0.8
  pretty_dio_logger: ^1.3.1
  gif_view: ^1.0.3
  dotted_line:
  hive_flutter:
  flutter_native_contact_picker: ^0.0.10
  flutter_contacts: ^1.1.9+2
  iconly: 
  permission_handler: ^12.0.0+1
  upgrader: ^11.5.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  flutter_svg: ^2.0.9
  share_plus: ^11.0.0
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  url_launcher: 
  country_picker: ^2.0.27
  camera: ^0.11.2
  image: ^4.1.7
  audioplayers: ^5.2.1
  country_state_picker: ^0.0.5
  glassmorphism_widgets: ^0.2.2
  #<<<< web view
  flutter_inappwebview: ^6.1.5   

  flutter_widget_from_html: ^0.16.0
  #web view
  flutter_slidable: ^4.0.0

  flutter_otp_text_field: ^1.1.0+2
  dotted_border: ^2.1.0
  file_picker: ^10.1.9


  video_player: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ie_logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/dashboard/
    - assets/images/svg/
    - assets/sounds/

  fonts:
    - family: NimbusSanLBol
      fonts:
        - asset: assets/fonts/NimbusSanL-Bol.otf

    - family: NimbusSanLBolIta
      fonts:
        - asset: assets/fonts/NimbusSanL-BolIta.otf

    - family: NimbusSanLRegular
      fonts:
        - asset: assets/fonts/NimbusSanL-Reg.otf

    - family: NimbusSanLRegularItalic
      fonts:
        - asset: assets/fonts/NimbusSanL-RegIta.otf

    - family: VahidRegular
      fonts:
        - asset: assets/fonts/XM-Vahid-Reg.otf

    - family: VahidRegularItalic
      fonts:
        - asset: assets/fonts/XM-Vahid-RegIta.otf

    - family: VahidBold
      fonts:
        - asset: assets/fonts/XM-Vahid-Bol.otf

    - family: VahidBoldItalic
      fonts:
        - asset: assets/fonts/XM-Vahid-BolIta.otf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Reg.otf

    - family: InterRegularItalic
      fonts:
        - asset: assets/fonts/Inter-RegIta.otf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bol.otf

    - family: InterBoldItalic
      fonts:
        - asset: assets/fonts/Inter-BolIta.otf

    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
